name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to vercel
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Merge to branch vercel
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: vercel
          github_token: ${{ secrets.CR_PAT }}
